Repository Ruhrpottpatriot/OnlineSubsystemEpic, pull requests merged in 2020-07, with the labels that each got.

#24 Make address of DevAuthTool customizable
  README.md
  Source/OnlineSubsystemEpic/Private/OnlineIdentityInterfaceEpic.cpp
  Source/OnlineSubsystemEpic/Private/OnlineSubsystemEpic.cpp
  Source/OnlineSubsystemEpic/Public/OnlineSubsystemEpic.h
Labels: Breaking, enhancement

#29 Add support for connect login and support for external account creation
  README.md
  Source/OnlineSubsystemEpic/Classes/EpicOnlineServicesLoginTask.cpp
  Source/OnlineSubsystemEpic/Classes/EpicOnlineServicesLoginTask.h
  Source/OnlineSubsystemEpic/Private/OnlineIdentityInterfaceEpic.cpp
  Source/OnlineSubsystemEpic/Private/OnlineIdentityInterfaceEpic.h
Labels: breaking, documentation, enhancement

#31 Bug/user info query
  CHANGELOG.md
  Source/OnlineSubsystemEpic/Classes/EpicOnlineServicesLoginTask.cpp
  Source/OnlineSubsystemEpic/Private/OnlineIdentityInterfaceEpic.cpp
  Source/OnlineSubsystemEpic/Private/OnlinePresenceEpic.cpp
  Source/OnlineSubsystemEpic/Private/OnlinePresenceEpic.h
  Source/OnlineSubsystemEpic/Private/OnlineSubsystemEpicTypes.h
  Source/OnlineSubsystemEpic/Private/OnlineUserInterfaceEpic.cpp
  Source/OnlineSubsystemEpic/Private/OnlineUserInterfaceEpic.h
  Source/OnlineSubsystemEpic/Public/OnlineSubsystemEpic.h
Labels: breaking, bug
